apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  hostPath:
    path: /srv/rfid-orders
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-pvc
  namespace: rfid
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
