name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push each microservice image
      - name: Build and push catalog service
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/catalog-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog-service:latest
          push: true

      - name: Build and push cart service
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/cart-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cart-service:latest
          push: true

      - name: Build and push checkout service
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/checkout-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/checkout-service:latest
          push: true

      - name: Build and push email service
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/email-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/email-service:latest
          push: true

      - name: Build and push orders service
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/orders-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/orders-service:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./rfid-card-app/frontend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          push: true

  # Optional deploy job via ArgoCD. This assumes you have an ArgoCD
  # application defined that references your Kubernetes manifests in
  # rfid-card-app/k8s-manifests. The job logs into ArgoCD using
  # credentials stored in GitHub Secrets and triggers a sync.
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 0755 argocd /usr/local/bin/argocd

      - name: Login to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure

      - name: Sync ArgoCD application
        env:
          ARGOCD_APP: ${{ secrets.ARGOCD_APP_NAME }}
        run: |
          argocd app sync "$ARGOCD_APP"
